import {useState} from 'react'
import type {CaseStudy} from '../data/caseStudies'
export function BotDemo({project}:{project:CaseStudy}) {
  const [step,setStep]=useState(0)
  const [value,setValue]=useState('')
  const [item,setItem]=useState('')
  const twitch=project.id==='twitch-vibe', limits=project.id==='neurosubs', wishes=project.id==='our-wants'
  const initial=limits?'Демо-аккаунты\nClaude · личный: осталось 27%\nCodex · рабочий: осталось 61%':twitch?'Чат предлагает идеи. Автор решает, что реализовать.':wishes?'Наш общий список\n☐ Поездка к морю\n☐ Кофемолка':'Мои задачи\n☐ Подготовиться к встрече'
  const action=limits?(step?'Вернуть исходное состояние':'Показать сброс окна'):twitch?(['Предложить идею','Проголосовать +1','Одобрить идею','Начать заново'][step]):step?'Отметить выполненным':wishes?'Добавить желание':'Добавить задачу'
  function run(){if(limits){setStep(step?0:1);return}if(twitch){setStep((step+1)%4);return}if(step===0){setItem(value.trim()||(wishes?'Поехать в горы':'Посмотреть портфолио'));setValue('');setStep(1)}else setStep(2)}
  return <div className="bot-demo"><div className="bot-explanation"><span className="eyebrow">Попробуйте сценарий</span><h3>Просто нажмите.<br/>Бот ответит.</h3><p>Интерактивная иллюстрация логики проекта, не подключённый Telegram-бот. Только демоданные; сообщения, уведомления и PR никуда не отправляются.</p><div className="stack-tags">{project.features.map(f=><span key={f}>{f}</span>)}</div></div><div className="bot-phone"><div className="bot-top"><span className="bot-avatar">{twitch?'↗':'✦'}</span><div><strong>{project.title}</strong><small>локальный симулятор</small></div><button aria-label="Сбросить сценарий" onClick={()=>{setStep(0);setItem('');setValue('')}}>↻</button></div><div className="bot-messages" aria-live="polite"><div className="bot-bubble">{initial}</div>{limits&&step>0&&<><div className="bot-bubble outgoing">Обновить лимиты</div><div className="bot-bubble">Окно Claude сбросилось. Доступно 100%.<br/>Одно уведомление на сброс — без повторов.</div></>}{twitch&&step>0&&<><div className="bot-bubble outgoing">[IDEA] Добавить тёмную тему</div><div className="bot-bubble">Идея #1 в очереди · {step>1?'3':'2'} голоса{step===2?' · ждёт одобрения':''}</div>{step===3&&<div className="bot-bubble">✓ Одобрено автором.<br/>Следующий шаг: отдельная ветка → реализация → PR.<br/>В симуляторе PR не создаётся.</div>}</>}{item&&<><div className="bot-bubble outgoing">{item}</div><div className="bot-bubble">{step===2?'✓ Выполнено':'☐ Добавлено в список'}: {item}</div></>}</div>{!limits&&!twitch&&step===0&&<input maxLength={100} aria-label={wishes?'Новое желание':'Новая задача'} placeholder={wishes?'О чём мечтаете?':'Что нужно сделать?'} value={value} onChange={e=>setValue(e.target.value)}/>}<button className="bot-action" disabled={!limits&&!twitch&&step===2} onClick={run}>{step===2&&!limits&&!twitch?'✓ Готово':action}</button></div></div>
}
